version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kasir_laundry_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kasir_laundry
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
