[build]
  command = "npm run build --workspace=frontend"
  publish = "frontend/dist"

[build.environment]
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
